spring:
  main:
    lazy-initialization: true
  r2dbc:
    url: r2dbc:pool:postgresql://127.0.0.1:5432/rsocket?currentSchema=account
    username: account
    password: 123456
    pool:
      enabled: true
      initial-size: 1
      max-size: 3

logging:
  level:
    io:
      r2dbc:
        postgresql:
          PARAM: DEBUG # for parameters
    org:
      springframework:
        r2dbc: DEBUG