spring:
  main:
    lazy-initialization: false
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/rsocket?currentSchema=account
    username: account
    password: 123456
    pool:
      enabled: true
      initial-size: 1
      max-size: 3

logging:
  level:
    io:
      r2dbc:
        postgresql:
          PARAM: DEBUG
    org:
      springframework:
        r2dbc: DEBUG

service:
  auth:
    host: localhost
    port: 7001